[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 9000
  targetPort = 3000

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]
  included_files = ["netlify/functions/utils/**"]

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/_next/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.ts"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.tsx"
    [headers.values]
    Content-Type = "application/javascript"
